:verbose: true
:concurrency: 8
:logfile: ./log/sidekiq.json.log
:queues:
  - scheduled_publishing
  - default
  - publishing_api
  - asset_manager
  - email_alert_api_signup
  - bulk_republishing
  - link_checks
  - asset_migration
:schedule:
  check_all_organisations_links_worker:
    cron: '0 4 * * *' # Runs at 4 a.m every day
    class: CheckAllOrganisationsLinksWorker
